name: Restricted workflow
on:
  push

jobs:
  build:
    name: "job_1"
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Reveal my secrets
        run: echo ${{ secrets.SECRET_TEST }}
